
name: '[builder] CI for releases'

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v1
        -
            name: Dockerhub login
            env:
                GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
                GITHUB_USERNAME: ${{ github.actor }}
            run: |
                echo "${GITHUB_TOKEN}" | docker login ghcr.io --username ${GITHUB_USERNAME} --password-stdin
        -
            uses: docker/setup-buildx-action@v1
            id: buildx
            with:
              install: true
        -
            name: Build dockerfile (with push)
            run: |
                docker build \
                --platform=linux/amd64,linux/arm/v7,linux/arm64 \
                --output "type=image,push=true" \
                --file ./Dockerfile . \
                --tag ghcr.io/gimse/pipelinetest/pipeline-test:5.3
